services:
  server:
    build:
      context: ..
    env_file:
      - ../.env.docker
    ports:
      - 3065:3065
  
#docker compose -f .docker/development.yaml -p blockchain-auth-service up --build -d 