type AuthenticationData {
  chain: String!
  address: String!
}

type Query {
  authenticationData(input: GetAuthenticationDataInput!): AuthenticationData
}

input GetAuthenticationDataInput {
  authenticationId: String!
}