type GetAuthenticationDataResult {
  chain: String!
}

type Query {
  authenticationData(input: GetAuthenticationDataInput!): GetAuthenticationDataResult
}

input GetAuthenticationDataInput {
  authenticationId: String!
}