name: Deploy on self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
 
    - name: Run `docker compose`
      env:
        PORT: ${{vars.PORT}}
        NODE_ENV: ${{vars.NODE_ENV}}
        REDIS_PORT: ${{secrets.REDIS_PORT}}
        REDIS_HOST: ${{secrets.REDIS_HOST}}
        SALT: ${{secrets.SALT}}
  
      run: docker compose -f .docker/production.yaml -p blockchain-auth-service up --build -d 
 